問題１  
内包表記を使って０から９９までを持つリストtest_listを作成してください。

Problem 1  
Create a list test_list with numbers from 0 to 99 using list comprehension.

In [ ]:
test_list = [i for i in range(100)]
#print(test_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


問題２  
スライスを使って、リストtest_listから５の倍数を**昇順**（小さいから大きい値への順番)に抜き出してください。

Problem 2  
Use slicing to extract multiples of 5 from list test_list in ascending order.

In [ ]:
# まず、test_list が存在することを確認します（問題1で作成したもの）

# スライスを使って5の倍数を抽出する
multiples_of_5 = test_list[::5]
print(multiples_of_5)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


問題３  
スライスを使って、リストtest_listから７の倍数を**降順**(大きい値から小さい値への順番)に抜き出してください。

Problem 3  
Use slicing to extract multiples of 7 from list test_list in descending order.

In [ ]:
# スライスを使って7の倍数を抽出し、降順に並べる
# test_list[98::-7] はインデックス98から始まり、ステップ-7で先頭まで値を取得する
# 98 は test_list の中で最後の7の倍数（7×14）のインデックス
multiples_of_7_descending = test_list[98::-7]

# 結果を出力
print(multiples_of_7_descending)

[98, 91, 84, 77, 70, 63, 56, 49, 42, 35, 28, 21, 14, 7, 0]


問題４  
numpyを使って、平均値ゼロ標準偏差１の標準正規分布となる乱数を100こ作成して、その配列をrnd_listとしてください。

Problem 4  
Use numpy to create 100 random numbers that have a standard normal distribution with a mean of zero and a standard deviation of 1, and set the array as rnd_list.

In [13]:
# numpy ライブラリをインポート、通常は np として省略される
import numpy as np

# numpy.random.randn() を使って100個の乱数を生成
# これらの乱数は標準正規分布（平均0、標準偏差1）に従う
rnd_list = np.random.randn(100)

# 生成された numpy 配列を出力
print(rnd_list)

[ 0.94125164 -0.12823732 -0.65508465 -0.00826718  0.52144321  0.41910826
  1.32777819  0.48593876  2.79814665  0.85742373 -0.91682382 -1.92397583
 -0.14014453  1.27607334  1.48654599 -0.87331592  0.89009706 -1.7404749
 -1.29695983 -1.80454313  0.20627839 -1.12561679  0.06556462  1.50880515
  0.56460103 -1.81067348 -0.85892308 -0.4628999   0.55084781 -2.24699932
  0.13131995 -2.47491653  0.25410166  1.29531621  0.12137442  0.0055825
  1.14261243 -0.45761133  0.69402848 -0.12122814 -0.41741072  0.29255707
 -1.47969591  0.02288526  0.10490574  0.96183693  1.54073574 -0.37560419
 -0.03310315 -0.89194809 -0.44860811  0.49439364 -0.45780862 -0.2441091
  0.79174562  0.65959869  0.36331771 -1.37274061  0.36701103 -1.50254331
  1.633938    1.17252932 -1.16504596 -0.03274655 -1.07349518  0.28188056
  1.35457485 -0.86330582 -1.14286999  0.5833251  -0.47236436 -0.64407023
  0.07936899  0.87869677  0.33520215 -1.22400366 -0.10720821 -0.11802418
  0.96826739 -0.03709707  2.0984796   0.26008589  0.70

問題５  
rnd_listの平均値と標準偏差を求めてください。

Problem 5  
Find the mean and standard deviation of rnd_list.

In [15]:
# rnd_list が存在することを確認 (問題4で生成)
# 未定義または別環境では以下を有効に:
# import numpy as np
# rnd_list = np.random.randn(100)

# 平均
mean_rnd = np.mean(rnd_list)
# 標準偏差
std_dev_rnd = np.std(rnd_list)

# 結果表示
print(f"平均値 (Mean): {mean_rnd}")
print(f"標準偏差 (Standard Deviation): {std_dev_rnd}")


平均値 (Mean): 0.06122398685334643
標準偏差 (Standard Deviation): 1.0089074291144595


問題６  
rnd_listを１０行１０列の行列に変換してrnd_matとして、そのサイズを表示させて１０行１０列であることを確認してください。

Problem 6  
Convert rnd_list to a matrix of 10 rows and 10 columns as rnd_mat and display its size to check.

In [17]:
# 将 rnd_list (包含100个元素) 重塑为 10x10 的矩阵
rnd_mat = rnd_list.reshape(10, 10)

# 显示 rnd_mat 的尺寸 (形状)
print("rnd_mat 的尺寸 (Shape):")
print(rnd_mat.shape)

# print("rnd_mat 矩阵:")
# print(rnd_mat)

rnd_mat 的尺寸 (Shape):
(10, 10)


問題７  
rnd_matの逆行列を求め、その行列とrnd_matの行列積を取った時に単位行列となることを確認してください。  
必要なら微小な値を無視する関数round_npを使用してください。

Problem 7  
Find the inverse matrix of rnd_mat and check that the matrix product of that matrix and rnd_mat yields a unit matrix.  
If necessary, use the round_np function to ignore small values.

In [22]:
# 微小な値を無視する関数の定義
def round_np(nparray):
    sh = nparray.shape
    res = np.array( # 小数点10桁で四捨五入
        [round(e, 10) for e in nparray.reshape(-1)]
        )
    return res.reshape(sh)

In [23]:
# round_np 関数を定義済みとする
# rnd_mat が存在することを確認 (問題6で生成)

# 逆行列を計算
# np.linalg.inv() で求める
try:
    rnd_mat_inv = np.linalg.inv(rnd_mat)

    # 元の行列と逆行列の積
    identity_check = rnd_mat_inv @ rnd_mat

    # 誤差除去のため round_np 処理
    identity_check_rounded = round_np(identity_check)

    # 結果表示
    print("逆行列と元の行列の積 (round_np 後):")
    print(identity_check_rounded)

except np.linalg.LinAlgError:
    # 逆行列が存在しない場合
    print("エラー: rnd_mat は特異行列で逆行列なし。")
    # この場合は以降の処理不可


逆行列と元の行列の積 (round_np 後):
[[ 1. -0. -0.  0.  0. -0.  0. -0. -0.  0.]
 [-0.  1.  0. -0. -0. -0. -0.  0.  0. -0.]
 [-0. -0.  1.  0.  0.  0. -0. -0.  0. -0.]
 [ 0.  0.  0.  1. -0. -0. -0.  0.  0.  0.]
 [ 0. -0. -0.  0.  1.  0.  0. -0. -0. -0.]
 [-0.  0. -0. -0.  0.  1.  0. -0. -0.  0.]
 [-0. -0.  0. -0. -0. -0.  1.  0. -0. -0.]
 [ 0.  0. -0. -0. -0.  0.  0.  1.  0.  0.]
 [-0. -0.  0.  0.  0. -0. -0.  0.  1. -0.]
 [ 0.  0. -0. -0. -0.  0. -0. -0. -0.  1.]]


問題８  
銀行口座を表すクラスを作成して、1000円を預け入れ、500円を引き出し、残高を表示してください。また更に1000円を引き出してください。
但し、クラスは下のような仕様を持つものとします。  

クラス：  
    BankAccount : 銀行口座  
属性：  
    - owner : 口座名義  
    - balance : 残高  
メソッド：  
    - deposit(amount) : amount円を預け入れる  
    - withdraw(amount) : amountを引き出す。残高が足りない場合は"Insufficient balance"と表示する。  
    - show_balance() : 残高を表示する。   

In [ ]:
# 銀行口座クラス
class BankAccount:
    # 初期化
    def __init__(self, owner, balance=0):
        """
        :param owner: 口座名義人 (文字列)
        :param balance: 初期残高 (デフォルト0)
        """
        self.owner = owner
        self.balance = balance
        print(f"{self.owner} の口座を作成、初期残高: {self.balance}円")

    # 入金
    def deposit(self, amount):
        """
        :param amount: 入金額 (正数)
        """
        if amount > 0:
            self.balance += amount
            print(f"{amount}円 入金完了")
            self.show_balance()
        else:
            print("入金は正の数のみ")

    # 出金
    def withdraw(self, amount):
        """
        :param amount: 出金額 (正数)
        """
        if amount <= 0:
            print("出金は正の数のみ")
        elif self.balance >= amount:
            self.balance -= amount
            print(f"{amount}円 出金完了")
            self.show_balance()
        else:
            print("残高不足")
            self.show_balance()

    # 残高表示
    def show_balance(self):
        print(f"現在の残高: {self.balance}円")

# --- 処理実行 ---

# 1. 口座作成
my_account = BankAccount("MyAccount")

# 2. 1000円 入金
print("\n--- 1000円 入金 ---")
my_account.deposit(1000)

# 3. 500円 出金
print("\n--- 500円 出金 ---")
my_account.withdraw(500)

# 4. 1000円 出金 (失敗)
print("\n--- 1000円 出金試行 ---")
my_account.withdraw(1000)


MyAccount の口座を作成、初期残高: 0円

--- 1000円 入金 ---
1000円 入金完了
現在の残高: 1000円

--- 500円 出金 ---
500円 出金完了
現在の残高: 500円

--- 1000円 出金試行 ---
残高不足
現在の残高: 500円
